-- NUMBER9 — Schema Cleanup: fix SECURITY DEFINER search_path, drop dead functions
--
-- Fixes:
--   1. Add missing SET search_path to 5 SECURITY DEFINER functions
--   2. Drop 6 dead audit helper functions (no callers, no grants needed)
--   3. Drop 2 dead trigger functions referencing non-existent columns
--   4. Remove grants from dead functions
--   5. ANALYZE for fresh stats

BEGIN;

-- =============================================================================
-- 1. FIX MISSING SET search_path ON SECURITY DEFINER FUNCTIONS
-- =============================================================================

-- session_heartbeat (called by React app via RPC)
CREATE OR REPLACE FUNCTION session_heartbeat(p_fingerprint TEXT DEFAULT NULL)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = 'public'
AS $$
DECLARE
  v_user_id UUID;
  v_session_token TEXT;
BEGIN
  v_session_token := current_setting('request.headers', true)::json->>'x-user-token';
  IF v_session_token IS NULL THEN RETURN; END IF;
  SELECT id INTO v_user_id FROM users
    WHERE session_token = encode(digest(v_session_token, 'sha256'), 'hex') AND session_expires_at > NOW();
  IF v_user_id IS NULL THEN RETURN; END IF;
  PERFORM update_session_heartbeat(v_user_id, p_fingerprint);
END;
$$;

-- update_session_heartbeat (internal, called by session_heartbeat)
CREATE OR REPLACE FUNCTION update_session_heartbeat(
  p_user_id UUID,
  p_fingerprint TEXT DEFAULT NULL
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = 'public'
AS $$
BEGIN
  UPDATE sessions
  SET
    last_activity = NOW(),
    device_info = CASE
      WHEN p_fingerprint IS NOT NULL THEN jsonb_build_object('fingerprint', p_fingerprint)
      ELSE device_info
    END
  WHERE user_id = p_user_id
    AND logged_out_at IS NULL
    AND (last_activity IS NULL OR last_activity < NOW() - INTERVAL '10 seconds');
END;
$$;

-- get_online_users (admin read-only)
CREATE OR REPLACE FUNCTION get_online_users()
RETURNS TABLE (
  user_id UUID,
  last_activity TIMESTAMP,
  ip_address TEXT,
  device_info JSONB
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = 'public'
AS $$
BEGIN
  RETURN QUERY
  SELECT DISTINCT ON (s.user_id)
    s.user_id, s.last_activity, s.ip_address, s.device_info
  FROM sessions s
  WHERE s.logged_out_at IS NULL
    AND s.last_activity > NOW() - INTERVAL '5 minutes'
  ORDER BY s.user_id, s.last_activity DESC;
END;
$$;

-- check_realtime_status (admin debug)
DROP FUNCTION IF EXISTS check_realtime_status();
CREATE OR REPLACE FUNCTION check_realtime_status()
RETURNS TABLE(channel TEXT, status TEXT, updated_at TIMESTAMP)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = 'public'
AS $$
BEGIN
  RETURN QUERY SELECT 'realtime_disabled'::TEXT, 'off'::TEXT, NOW()::TIMESTAMP;
END;
$$;

-- prune_old_audit_logs (called by pg_cron)
CREATE OR REPLACE FUNCTION prune_old_audit_logs()
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = 'public'
AS $$
BEGIN
  DELETE FROM audit_log WHERE created_at < NOW() - INTERVAL '90 days';
END;
$$;

-- =============================================================================
-- 2. DROP DEAD FUNCTIONS — no callers, superseded by Edge Functions
-- =============================================================================

-- fn_record_failed_login: brute-force tracking — not wired to any login flow
DROP FUNCTION IF EXISTS fn_record_failed_login(VARCHAR, VARCHAR, VARCHAR, TEXT);

-- fn_create_session: superseded by Edge Function user-login
DROP FUNCTION IF EXISTS fn_create_session(UUID, VARCHAR, VARCHAR, TEXT, JSONB, TEXT);

-- fn_end_session: superseded by Edge Function auth-logout
DROP FUNCTION IF EXISTS fn_end_session(UUID, VARCHAR, VARCHAR);

-- fn_record_user_change: audit — superseded by triggers
DROP FUNCTION IF EXISTS fn_record_user_change(UUID, UUID, VARCHAR, JSONB, JSONB, TEXT, TEXT);

-- fn_record_transaction_change: audit — superseded by triggers
DROP FUNCTION IF EXISTS fn_record_transaction_change(UUID, UUID, VARCHAR, VARCHAR, VARCHAR, TEXT, VARCHAR);

-- fn_create_security_alert: never integrated
DROP FUNCTION IF EXISTS fn_create_security_alert(VARCHAR, VARCHAR, UUID, VARCHAR, TEXT, JSONB);

-- fn_record_user_change: audit — superseded by triggers
DROP FUNCTION IF EXISTS fn_record_user_change(UUID, UUID, VARCHAR, JSONB, JSONB, TEXT, VARCHAR);

-- =============================================================================
-- 3. DROP DEAD TRIGGER FUNCTIONS — reference columns that may not exist
-- =============================================================================

-- trg_set_user_short_code: references short_code column — column not in schema
DROP TRIGGER IF EXISTS trg_user_short_code ON users;
DROP FUNCTION IF EXISTS trg_set_user_short_code();

-- trg_set_transaction_code: references reference_code column — generated by trigger
DROP TRIGGER IF EXISTS trg_transaction_reference_code ON transactions;
DROP FUNCTION IF EXISTS trg_set_transaction_code();

-- =============================================================================
-- 5. ANALYZE
-- =============================================================================
ANALYZE audit_log;
ANALYZE sessions;

COMMIT;
